express = require('express')
router = express.Router()
config = require('../../../config.json')
router.get '/api', (req, res) ->
  res.json
    name: config.api.name
    url: config.api.url
  return
module.exports = router

# ---
# generated by js2coffee 2.0.3